### ISSUE TITLE
Would you like to use json file for the resource?

### ISSUE THREAD

**Issue by wsdjeg** [Codingpedia/dev-resources#1]
I just create a new plugin to quick view cheatsheets, and by default I use [git-tips](https://github.com/git-tips/tips) and [simplesheets](https://github.com/artur-shaik/simplecheats) as upstream.  I also want to use this repo as a upstream, so maybe a json file will be better. for example, I use a link in this repo, and the plugin I just wrote.

``` json
[
    { "name" : "vim-cheat",
       "url" : "https://github.com/wsdjeg/vim-cheat",
       "desc" : "View cheatsheets via vim",
       "tag" : "vim"
    },
    { "name" : "Single Table Inheritance",
      "url":"http://martinfowler.com/eaaCatalog/singleTableInheritance.html",
      "desc":"represents an inheritance hierarchy of classes as a single table that has columns for all the fields of the various classes. [db design table inheritance, design patterns, eaa]",
      "tag":"Database Design"
    }
]
```

BTW, you can add anyother keys.

**Comment by wsdjeg** [comment]
@amacoder Ping!

**Comment by adirochs** [comment]
Hi @wsdjeg , 
That sounds like a great idea - have some json file with a format similar to what you suggest, and with a javascript/java program generate the resulting README.md file...

Thanks,
Adrian

**Comment by wsdjeg** [comment]
Thanks,
